apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-source-config
  namespace: default
data:
  catalog: '{
    "streams": [
        {
            "sync_mode": "full_refresh",
            "destination_sync_mode": "overwrite",
            "stream": {
                "name": "UserApiToken",
                "json_schema": {
                    "properties": {
                        "createdAt": {
                            "type": "string",
                            "format": "date-time"
                        },
                        "hash": {
                            "type": "string"
                        },
                        "hint": {
                            "type": "string"
                        },
                        "id": {
                            "type": "string"
                        },
                        "updatedAt": {
                            "type": "string",
                            "format": "date-time"
                        },
                        "userId": {
                            "type": "string"
                        }
                    }
                },
                "supported_sync_modes": [
                    "full_refresh",
                    "incremental"
                ],
                "source_defined_primary_key": [
                    [
                        "id"
                    ]
                ],
                "source_defined_cursor": false,
                "namespace": "newjitsu"
            }
        },
        {
            "sync_mode": "full_refresh",
            "destination_sync_mode": "overwrite",
            "stream": {
                "name": "ConfigurationObjectLink",
                "json_schema": {
                    "properties": {
                        "createdAt": {
                            "type": "string",
                            "format": "date-time"
                        },
                        "data": {
                            "type": "string"
                        },
                        "deleted": {
                            "type": "boolean"
                        },
                        "fromId": {
                            "type": "string"
                        },
                        "id": {
                            "type": "string"
                        },
                        "toId": {
                            "type": "string"
                        },
                        "updatedAt": {
                            "type": "string",
                            "format": "date-time"
                        },
                        "workspaceId": {
                            "type": "string"
                        }
                    }
                },
                "supported_sync_modes": [
                    "full_refresh",
                    "incremental"
                ],
                "source_defined_primary_key": [
                    [
                        "id"
                    ]
                ],
                "source_defined_cursor": false,
                "namespace": "newjitsu"
            }
        },
        {
            "sync_mode": "full_refresh",
            "destination_sync_mode": "overwrite",
            "stream": {
                "name": "WorkspaceAccess",
                "json_schema": {
                    "properties": {
                        "createdAt": {
                            "type": "string",
                            "format": "date-time"
                        },
                        "updatedAt": {
                            "type": "string",
                            "format": "date-time"
                        },
                        "userId": {
                            "type": "string"
                        },
                        "workspaceId": {
                            "type": "string"
                        }
                    }
                },
                "supported_sync_modes": [
                    "full_refresh",
                    "incremental"
                ],
                "source_defined_primary_key": [
                    [
                        "userId"
                    ],
                    [
                        "workspaceId"
                    ]
                ],
                "source_defined_cursor": false,
                "namespace": "newjitsu"
            }
        },
        {
            "sync_mode": "full_refresh",
            "destination_sync_mode": "overwrite",
            "stream": {
                "name": "Workspace",
                "json_schema": {
                    "properties": {
                        "createdAt": {
                            "type": "string",
                            "format": "date-time"
                        },
                        "deleted": {
                            "type": "boolean"
                        },
                        "id": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        },
                        "slug": {
                            "type": "string"
                        },
                        "updatedAt": {
                            "type": "string",
                            "format": "date-time"
                        }
                    }
                },
                "supported_sync_modes": [
                    "full_refresh",
                    "incremental"
                ],
                "source_defined_primary_key": [
                    [
                        "id"
                    ]
                ],
                "source_defined_cursor": false,
                "namespace": "newjitsu"
            }
        },
        {
            "sync_mode": "full_refresh",
            "destination_sync_mode": "overwrite",
            "stream": {
                "name": "InvitationToken",
                "json_schema": {
                    "properties": {
                        "createdAt": {
                            "type": "string",
                            "format": "date-time"
                        },
                        "email": {
                            "type": "string"
                        },
                        "id": {
                            "type": "string"
                        },
                        "token": {
                            "type": "string"
                        },
                        "updatedAt": {
                            "type": "string",
                            "format": "date-time"
                        },
                        "usedBy": {
                            "type": "string"
                        },
                        "workspaceId": {
                            "type": "string"
                        }
                    }
                },
                "supported_sync_modes": [
                    "full_refresh",
                    "incremental"
                ],
                "source_defined_primary_key": [
                    [
                        "id"
                    ]
                ],
                "source_defined_cursor": false,
                "namespace": "newjitsu"
            }
        },
        {
            "sync_mode": "full_refresh",
            "destination_sync_mode": "overwrite",
            "stream": {
                "name": "UserPreferences",
                "json_schema": {
                    "properties": {
                        "createdAt": {
                            "type": "string",
                            "format": "date-time"
                        },
                        "id": {
                            "type": "string"
                        },
                        "preferences": {
                            "type": "string"
                        },
                        "scope": {
                            "type": "string"
                        },
                        "updatedAt": {
                            "type": "string",
                            "format": "date-time"
                        },
                        "userId": {
                            "type": "string"
                        },
                        "workspaceId": {
                            "type": "string"
                        }
                    }
                },
                "supported_sync_modes": [
                    "full_refresh",
                    "incremental"
                ],
                "source_defined_primary_key": [
                    [
                        "id"
                    ]
                ],
                "source_defined_cursor": false,
                "namespace": "newjitsu"
            }
        },
        {
            "sync_mode": "full_refresh",
            "destination_sync_mode": "overwrite",
            "stream": {
                "name": "EmailLog",
                "json_schema": {
                    "properties": {
                        "email": {
                            "type": "string"
                        },
                        "error": {
                            "type": "string"
                        },
                        "id": {
                            "type": "string"
                        },
                        "messageId": {
                            "type": "string"
                        },
                        "previewUrl": {
                            "type": "string"
                        },
                        "status": {
                            "type": "string"
                        },
                        "time": {
                            "type": "string",
                            "format": "date-time"
                        }
                    }
                },
                "supported_sync_modes": [
                    "full_refresh",
                    "incremental"
                ],
                "source_defined_primary_key": [
                    [
                        "id"
                    ]
                ],
                "source_defined_cursor": false,
                "namespace": "newjitsu"
            }
        },
        {
            "sync_mode": "full_refresh",
            "destination_sync_mode": "overwrite",
            "stream": {
                "name": "UserProfile",
                "json_schema": {
                    "properties": {
                        "admin": {
                            "type": "boolean"
                        },
                        "createdAt": {
                            "type": "string",
                            "format": "date-time"
                        },
                        "email": {
                            "type": "string"
                        },
                        "externalId": {
                            "type": "string"
                        },
                        "externalUsername": {
                            "type": "string"
                        },
                        "id": {
                            "type": "string"
                        },
                        "loginProvider": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        },
                        "updatedAt": {
                            "type": "string",
                            "format": "date-time"
                        }
                    }
                },
                "supported_sync_modes": [
                    "full_refresh",
                    "incremental"
                ],
                "source_defined_primary_key": [
                    [
                        "id"
                    ]
                ],
                "source_defined_cursor": false,
                "namespace": "newjitsu"
            }
        },
        {
            "sync_mode": "incremental",
            "destination_sync_mode": "overwrite",
            "cursor_field": [
                "updatedAt"
            ],
            "stream": {
                "name": "ConfigurationObject",
                "json_schema": {
                    "properties": {
                        "config": {
                            "type": "string"
                        },
                        "createdAt": {
                            "type": "string",
                            "format": "date-time"
                        },
                        "deleted": {
                            "type": "boolean"
                        },
                        "id": {
                            "type": "string"
                        },
                        "type": {
                            "type": "string"
                        },
                        "updatedAt": {
                            "type": "string",
                            "format": "date-time"
                        },
                        "workspaceId": {
                            "type": "string"
                        }
                    }
                },
                "supported_sync_modes": [
                    "full_refresh",
                    "incremental"
                ],
                "source_defined_primary_key": [
                    [
                        "id"
                    ]
                ],
                "source_defined_cursor": false,
                "namespace": "newjitsu"
            }
        }
    ]
}'
  config: '{"database":"d407fn369vu7fr","host":"tele.g.jitsu.com","password":"p492771b0cef7c52f715d9d7f09f114f60d0272d9361124b2b56b19d861f0e6e4","port":5432,"replication_method":{"method":"Standard"},"schemas":["newjitsu"],"ssl":false,"ssl_mode":{"mode":"disable"},"tunnel_method":{"tunnel_method":"NO_TUNNEL"},"username":"u8rug136k5pa6o"}'

---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-source
  namespace: default
  labels:
    app: postgres_source
spec:
  restartPolicy: Never
  volumes:
    - name: config
      configMap:
        name: postgres-source-config
        items:
          - key: config
            path: config.json
          - key: catalog
            path: catalog.json
    - name: pipes
      emptyDir: {}
  containers:
    - name: sidecar
      image: docker.io/jitsucom/sidecar:0.0.10
      env:
        - name: SOURCE_ID
          value: postgres
        - name: TASK_ID
          value: "1"
        - name: BULKER_URL
          value: http://host.docker.internal:3042
        - name: BULKER_AUTH_TOKEN
          value: 21a2ae36-32994870a9fbf2f61ea6f6c8
        - name: CONNECTION_ID
          value: clftsxwg90003cclqo3ai8z6s
        - name: TASKS_CONNECTION_ID
          value: tasks
        - name: STATE_CONNECTION_ID
          value: tasks_state
        - name: STDOUT_PIPE_FILE
          value: /pipes/stdout
        - name: STDERR_PIPE_FILE
          value: /pipes/stderr
      volumeMounts:
        - name: pipes
          mountPath: /pipes
    - name: postgres
      image: airbyte/source-postgres:2.0.13
      command: ['sh', '-c', 'eval "$AIRBYTE_ENTRYPOINT read --config /config/config.json --catalog /config/catalog.json" 2> /pipes/stderr > /pipes/stdout' ]
      volumeMounts:
        - name: config
          mountPath: /config
        - name: pipes
          mountPath: /pipes
  initContainers:
    - name: init
      image: busybox:1.36.0
      command: ["sh", "-c", "mkfifo /pipes/stdout; mkfifo /pipes/stderr"]
      volumeMounts:
        - name: pipes
          mountPath: /pipes

