destinations:
  batch_postgres:
    type: "postgres"
    options:
      mode: "batch"
      batchSize: 10
      primaryKey: "id"
    credentials:
      host: localhost
      port: [[POSTGRES_PORT]]
      database: test
      username: test
      password: test
      defaultSchema: bulker
      parameters:
        sslmode: disable
  stream_postgres:
    type: "postgres"
    options:
      mode: "stream"
      primaryKey: "id"
    credentials:
      host: localhost
      port: [[POSTGRES_PORT]]
      database: test
      username: test
      password: test
      defaultSchema: bulker
      parameters:
        sslmode: disable
  load_test_postgres:
    type: "postgres"
    options:
      mode: "batch"
      batchSize: 500000
    credentials:
      host: localhost
      port: [[POSTGRES_PORT]]
      database: test
      username: test
      password: test
      defaultSchema: bulker
      parameters:
        sslmode: disable
