version: "2.3"

services:
  init:
    container_name: init
    image: busybox:1.36.0
    volumes:
      - pipes:/pipes
    entrypoint: ["sh", "-c", "rm -f /pipes/*; mkfifo /pipes/stdout; mkfifo /pipes/stderr"]
    restart: "no"
  jitsu:
    container_name: github
    image: airbyte/source-github:0.4.3
    entrypoint: [ 'sh', '-c', 'eval "$$AIRBYTE_ENTRYPOINT spec" 2> /pipes/stderr > /pipes/stdout' ]
    #entrypoint: [ 'sh', '-c', 'eval "$$AIRBYTE_ENTRYPOINT read --config /config/config.json --catalog /config/catalog.json --state /config/state.json" 2> /pipes/stderr > /pipes/stdout' ]
    depends_on:
      init:
        condition: service_completed_successfully
    volumes:
      - ./config.json:/config/config.json
      - ./catalog.json:/config/catalog.json
      - ./state.json:/config/state.json
      - pipes:/pipes
    restart: "no"
  sidecar:
    container_name: sidecar
    image: jitsucom/sidecar:0.0.11
    volumes:
      - pipes:/pipes
    restart: "no"
    environment:
      SOURCE_ID: github
      TASK_ID: "1"
      BULKER_URL: http://host.docker.internal:3042
      BULKER_AUTH_TOKEN: 21a2ae36-32994870a9fbf2f61ea6f6c8
      CONNECTION_ID: clftsxwg90003cclqo3ai8z6s
      TASKS_CONNECTION_ID: tasks
      STATE_CONNECTION_ID: tasks_state
      STDOUT_PIPE_FILE: /pipes/stdout
      STDERR_PIPE_FILE: /pipes/stderr
    depends_on:
      init:
        condition: service_started

volumes:
  pipes:
    name: pipes
