destinations:
  batch_postgres:
    type: "postgres"
    mode: "batch"
    options:
      batchSize: 10
      primaryKey: "id"
    credentials:
      host: localhost
      port: [[POSTGRES_PORT]]
      database: test
      username: test
      password: test
      defaultSchema: bulker
      parameters:
        sslmode: disable
  stream_postgres:
    type: "postgres"
    mode: "stream"
    options:
      primaryKey: "id"
    credentials:
      host: localhost
      port: [[POSTGRES_PORT]]
      database: test
      username: test
      password: test
      defaultSchema: bulker
      parameters:
        sslmode: disable

