destinations:
  batch_postgres:
    type: "postgres"
    mode: "batch"
    batch_size: 10
    credentials:
      host: localhost
      port: [[POSTGRES_PORT]]
      database: test
      username: test
      password: test
      default_schema: bulker
      parameters:
        sslmode: disable
  stream_postgres:
    type: "postgres"
    mode: "stream"
    credentials:
      host: localhost
      port: [[POSTGRES_PORT]]
      database: test
      username: test
      password: test
      default_schema: bulker
      parameters:
        sslmode: disable

