version: '3.5'
services:
  zookeeper:
    image: zookeeper:3.7
    container_name: zookeeper
    hostname: zookeeper
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.10
  clickhouse01:
    image: clickhouse/clickhouse-server:22.8-alpine
    container_name: clickhouse01
    hostname: clickhouse01
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.11
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./clickhouse01:/etc/clickhouse-server
    healthcheck:
      test: [ "CMD-SHELL", "clickhouse-client --host clickhouse01 --query 'SELECT 1'" ]
      interval: 5s
      timeout: 3s
      retries: 30
    depends_on:
      - zookeeper
  clickhouse02:
    image: clickhouse/clickhouse-server:22.8-alpine
    container_name: clickhouse02
    hostname: clickhouse02
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.12
    ports:
      - "8124:8123"
      - "9001:9000"
    volumes:
      - ./clickhouse02:/etc/clickhouse-server
    healthcheck:
      test: [ "CMD-SHELL", "clickhouse-client --host clickhouse02 --query 'SELECT 1'" ]
      interval: 5s
      timeout: 3s
      retries: 30
    depends_on:
      - zookeeper
  clickhouse03:
    image: clickhouse/clickhouse-server:22.8-alpine
    container_name: clickhouse03
    hostname: clickhouse03
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.13
    ports:
      - "8125:8123"
      - "9002:9000"
    volumes:
      - ./clickhouse03:/etc/clickhouse-server
    healthcheck:
      test: [ "CMD-SHELL", "clickhouse-client --host clickhouse03 --query 'SELECT 1'" ]
      interval: 5s
      timeout: 3s
      retries: 30
    depends_on:
      - zookeeper
  clickhouse04:
    image: clickhouse/clickhouse-server:22.8-alpine
    container_name: clickhouse04
    hostname: clickhouse04
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.14
    ports:
      - "8126:8123"
      - "9003:9000"
    volumes:
      - ./clickhouse04:/etc/clickhouse-server
    healthcheck:
      test: [ "CMD-SHELL", "clickhouse-client --host clickhouse04 --query 'SELECT 1'" ]
      interval: 5s
      timeout: 3s
      retries: 30
    depends_on:
      - zookeeper

networks:
  clickhouse-network:
    name: clickhouse-network
    ipam:
      config:
        - subnet: 172.23.0.0/24
