name: Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false
      - name: Set outputs
        id: vars
        run: |
          echo "tag=$(echo ${{ github.ref_name }} | sed 's/v//')" >> $GITHUB_OUTPUT
          echo "timestamp=$(date '+%F_%H:%M:%S')" >> $GITHUB_OUTPUT
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: "bulker.Dockerfile"
          push: true
          build-args: |
            VERSION=${{ github.ref_name }}.${{ steps.short-sha.outputs.sha }}
            BUILD_TIMESTAMP=${{ steps.vars.outputs.timestamp }}
          tags: jitsucom/bulker:latest,jitsucom/bulker:${{ steps.vars.outputs.tag }}